language: objective-c
env:
  global:
  - secure: "W8vou0KRJOOboZXP9q+D/9Wl6LlBeVS2T85MHWPz7EwCMQbJq5xWnGzYLE6FmC0iILcZkXyP63vqoYMFo5MJaEQeALGx2RuIiW7XgrD+7Bn4Vfsp6BLT7K9/AJETGGTQnLs8oZJJCXHGtzbc8EPFIZd/ZPPrve4jhEE5ZNhXnRc="
  matrix:
  - CMAKE_CXX_COMPILER=g++ CMAKE_BUILD_TYPE=DEBUG   USE_TCMALLOC=TRUE  MEMCHECK=TRUE PUSH_TO_CDASH=TRUE
  - CMAKE_CXX_COMPILER=g++ CMAKE_BUILD_TYPE=DEBUG   USE_TCMALLOC=FALSE
  - CMAKE_CXX_COMPILER=g++ CMAKE_BUILD_TYPE=RELEASE USE_TCMALLOC=TRUE  UPLOAD=osx
  - CMAKE_CXX_COMPILER=g++ CMAKE_BUILD_TYPE=RELEASE USE_TCMALLOC=FALSE UPLOAD=osx_tcmalloc

before_script:
- mkdir -p build
- cd build
- CPLUS_INCLUDE_PATH=/usr/local/include/c++/4.9.0/:/usr/local/include/c++/4.9.0/x86_64-apple-darwin12.4.0:/usr/local/include/c++/4.9.0/bits/
- export CPLUS_INCLUDE_PATH
- LIBRARY_PATH=/usr/local/lib:/local/lib/gcc/x86_64-apple-darwin12.4.0/4.9.0/
- export LIBRARY_PATH
- cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_CXX_COMPILER=/usr/local/bin/${CMAKE_CXX_COMPILER} ../src -G Ninja
- cd ..

script:
- cd build
- ctest -D ExperimentalConfigure
- ctest -D ExperimentalBuild -VV
- yes "C" | ctest -D ExperimentalTest -VV
- if [[ $MEMCHECK == TRUE ]]; then
     ctest -D ExperimentalMemCheck;
  fi
- if [[ $PUSH_TO_CDASH == TRUE ]]; then
    ctest -D ExperimentalSubmit;
  fi
- cd ..

after_script:
- if [[ $UPLOAD ]]; then
      UPLOAD_DIR=bin;
      BINARY=lean_${UPLOAD};
      mkdir ${UPLOAD_DIR};
      cp build/shell/lean ${UPLOAD_DIR}/${BINARY};
      script/dropbox_upload.py ${UPLOAD_DIR} /Public/${UPLOAD_DIR} ${DROPBOX_KEY};
  fi

install:
- if [[ $CMAKE_CXX_COMPILER == g++ ]]; then
      cd /;
      wget http://dl.dropboxusercontent.com/u/203889738/gcc/gcc-4.9.0_OSX.tar.bz2 -O /tmp/gcc-mlion.tar.bz2;
      sudo tar xfj /tmp/gcc-mlion.tar.bz2;
      cd -;
      sudo chown -R `whoami` /usr/local;
      brew install gmp; brew link --overwrite gmp;
      brew install mpfr; brew link --overwrite mpfr;
  fi
- brew install cmake ninja
- if [[ $MEMCHECK == TRUE ]]; then
      brew install valgrind;
  fi
- if [[ $USE_TCMALLOC == TRUE ]]; then brew install google-perftools; fi
- if [[ $UPLOAD ]]; then
      brew install python; pip install dropbox;
  fi

notifications:
  email:
    recipients:
    - leansmt-dev@googlegroups.com
    on_success: always
    on_failure: always
