# As the PR author, use `!rebase` to rebase a commit
name: Rebase on Comment

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '!rebase') && github.event.comment.user.login == github.event.issue.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
      - name: Rebase PR branch onto base branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin refs/pull/${{ github.event.issue.number }}/base
          git rebase FETCH_HEAD
          git push --force-with-lease